# Generated by Django 4.2.7 on 2023-11-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homepage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail_title',
        ),
    ]
