# Generated by Django 4.2.7 on 2023-11-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_delete_homepage_remove_product_thumbnail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='img/products/'),
        ),
    ]
